//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class Configuration : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_baseUrl0;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_timeout1;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_pollingInterval2;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_holdBrowserOpen3;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_reopenBrowserOnFail4;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_openBrowserTimeoutMs5;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_closeBrowserTimeoutMs6;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_browser7;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_remote8;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_startMaximized9;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_clickViaJs10;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_screenshots11;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_reportsFolder12;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_reportsUrl13;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_dismissModalDialogs14;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_fastSetValue15;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_selectorMode16;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_assertionMode17;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorConfiguration18;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public Configuration() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n__ctorConfiguration18, this);
            }
        }
        
        protected Configuration(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.Configuration.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String baseUrl {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_baseUrl0));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("J")]
        public static long timeout {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((long)(@__env.GetStaticLongField(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_timeout1)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("J")]
        public static long pollingInterval {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((long)(@__env.GetStaticLongField(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_pollingInterval2)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Z")]
        public static bool holdBrowserOpen {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((bool)(@__env.GetStaticBooleanField(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_holdBrowserOpen3)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Z")]
        public static bool reopenBrowserOnFail {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((bool)(@__env.GetStaticBooleanField(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_reopenBrowserOnFail4)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("J")]
        public static long openBrowserTimeoutMs {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((long)(@__env.GetStaticLongField(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_openBrowserTimeoutMs5)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("J")]
        public static long closeBrowserTimeoutMs {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((long)(@__env.GetStaticLongField(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_closeBrowserTimeoutMs6)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String browser {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_browser7));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String remote {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_remote8));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Z")]
        public static bool startMaximized {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((bool)(@__env.GetStaticBooleanField(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_startMaximized9)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Z")]
        public static bool clickViaJs {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((bool)(@__env.GetStaticBooleanField(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_clickViaJs10)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Z")]
        public static bool screenshots {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((bool)(@__env.GetStaticBooleanField(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_screenshots11)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String reportsFolder {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_reportsFolder12));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String reportsUrl {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_reportsUrl13));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Z")]
        public static bool dismissModalDialogs {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((bool)(@__env.GetStaticBooleanField(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_dismissModalDialogs14)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Z")]
        public static bool fastSetValue {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((bool)(@__env.GetStaticBooleanField(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_fastSetValue15)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Configuration$SelectorMode;")]
        public static global::java.lang.Object selectorMode {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_selectorMode16));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Configuration$AssertionMode;")]
        public static global::java.lang.Object assertionMode {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Configuration.staticClass, global::com.codeborne.selenide.Configuration.j4n_assertionMode17));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.Configuration.staticClass = @__class;
            global::com.codeborne.selenide.Configuration.j4n_baseUrl0 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "baseUrl", "Ljava/lang/String;");
            global::com.codeborne.selenide.Configuration.j4n_timeout1 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "timeout", "J");
            global::com.codeborne.selenide.Configuration.j4n_pollingInterval2 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "pollingInterval", "J");
            global::com.codeborne.selenide.Configuration.j4n_holdBrowserOpen3 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "holdBrowserOpen", "Z");
            global::com.codeborne.selenide.Configuration.j4n_reopenBrowserOnFail4 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "reopenBrowserOnFail", "Z");
            global::com.codeborne.selenide.Configuration.j4n_openBrowserTimeoutMs5 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "openBrowserTimeoutMs", "J");
            global::com.codeborne.selenide.Configuration.j4n_closeBrowserTimeoutMs6 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "closeBrowserTimeoutMs", "J");
            global::com.codeborne.selenide.Configuration.j4n_browser7 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "browser", "Ljava/lang/String;");
            global::com.codeborne.selenide.Configuration.j4n_remote8 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "remote", "Ljava/lang/String;");
            global::com.codeborne.selenide.Configuration.j4n_startMaximized9 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "startMaximized", "Z");
            global::com.codeborne.selenide.Configuration.j4n_clickViaJs10 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "clickViaJs", "Z");
            global::com.codeborne.selenide.Configuration.j4n_screenshots11 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "screenshots", "Z");
            global::com.codeborne.selenide.Configuration.j4n_reportsFolder12 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "reportsFolder", "Ljava/lang/String;");
            global::com.codeborne.selenide.Configuration.j4n_reportsUrl13 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "reportsUrl", "Ljava/lang/String;");
            global::com.codeborne.selenide.Configuration.j4n_dismissModalDialogs14 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "dismissModalDialogs", "Z");
            global::com.codeborne.selenide.Configuration.j4n_fastSetValue15 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "fastSetValue", "Z");
            global::com.codeborne.selenide.Configuration.j4n_selectorMode16 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "selectorMode", "Lcom/codeborne/selenide/Configuration$SelectorMode;");
            global::com.codeborne.selenide.Configuration.j4n_assertionMode17 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Configuration.staticClass, "assertionMode", "Lcom/codeborne/selenide/Configuration$AssertionMode;");
            global::com.codeborne.selenide.Configuration.j4n__ctorConfiguration18 = @__env.GetMethodID(global::com.codeborne.selenide.Configuration.staticClass, "<init>", "()V");
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.Configuration(@__env);
            }
        }
    }
    #endregion
}
