//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class ElementsCollection : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_find0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_filter1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_first2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_last3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_shouldHave4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_shouldBe5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_filterBy6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_exclude7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_excludeWith8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_findBy9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getTexts10;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getTexts11;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_elementsToString12;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_shouldHaveSize13;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorElementsCollection14;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/impl/WebElementsCollection;)V")]
        public ElementsCollection(global::com.codeborne.selenide.impl.WebElementsCollection par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::com.codeborne.selenide.ElementsCollection.staticClass, global::com.codeborne.selenide.ElementsCollection.j4n__ctorElementsCollection14, this, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::com.codeborne.selenide.impl.WebElementsCollection>(@__env, par0));
            }
        }
        
        protected ElementsCollection(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.ElementsCollection.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.ElementsCollection.staticClass = @__class;
            global::com.codeborne.selenide.ElementsCollection.j4n_find0 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "find", "(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.ElementsCollection.j4n_filter1 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "filter", "(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/ElementsCollection;");
            global::com.codeborne.selenide.ElementsCollection.j4n_first2 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "first", "()Lcom/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.ElementsCollection.j4n_last3 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "last", "()Lcom/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.ElementsCollection.j4n_shouldHave4 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "shouldHave", "([Lcom/codeborne/selenide/CollectionCondition;)Lcom/codeborne/selenide/ElementsCo" +
                    "llection;");
            global::com.codeborne.selenide.ElementsCollection.j4n_shouldBe5 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "shouldBe", "([Lcom/codeborne/selenide/CollectionCondition;)Lcom/codeborne/selenide/ElementsCo" +
                    "llection;");
            global::com.codeborne.selenide.ElementsCollection.j4n_filterBy6 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "filterBy", "(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/ElementsCollection;");
            global::com.codeborne.selenide.ElementsCollection.j4n_exclude7 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "exclude", "(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/ElementsCollection;");
            global::com.codeborne.selenide.ElementsCollection.j4n_excludeWith8 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "excludeWith", "(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/ElementsCollection;");
            global::com.codeborne.selenide.ElementsCollection.j4n_findBy9 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "findBy", "(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.ElementsCollection.j4n_getTexts10 = @__env.GetStaticMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "getTexts", "(Ljava/util/Collection;)[Ljava/lang/String;");
            global::com.codeborne.selenide.ElementsCollection.j4n_getTexts11 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "getTexts", "()[Ljava/lang/String;");
            global::com.codeborne.selenide.ElementsCollection.j4n_elementsToString12 = @__env.GetStaticMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "elementsToString", "(Ljava/util/Collection;)Ljava/lang/String;");
            global::com.codeborne.selenide.ElementsCollection.j4n_shouldHaveSize13 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "shouldHaveSize", "(I)Lcom/codeborne/selenide/ElementsCollection;");
            global::com.codeborne.selenide.ElementsCollection.j4n__ctorElementsCollection14 = @__env.GetMethodID(global::com.codeborne.selenide.ElementsCollection.staticClass, "<init>", "(Lcom/codeborne/selenide/impl/WebElementsCollection;)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/SelenideElement;")]
        public virtual global::com.codeborne.selenide.SelenideElement find(global::com.codeborne.selenide.Condition par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.ElementsCollection.j4n_find0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/ElementsCollection;")]
        public virtual global::com.codeborne.selenide.ElementsCollection filter(global::com.codeborne.selenide.Condition par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.ElementsCollection.j4n_filter1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/codeborne/selenide/SelenideElement;")]
        public virtual global::com.codeborne.selenide.SelenideElement first() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.ElementsCollection.j4n_first2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/codeborne/selenide/SelenideElement;")]
        public virtual global::com.codeborne.selenide.SelenideElement last() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.ElementsCollection.j4n_last3));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([Lcom/codeborne/selenide/CollectionCondition;)Lcom/codeborne/selenide/ElementsCo" +
            "llection;")]
        public virtual global::com.codeborne.selenide.ElementsCollection shouldHave(global::com.codeborne.selenide.CollectionCondition[] par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.ElementsCollection.j4n_shouldHave4, global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([Lcom/codeborne/selenide/CollectionCondition;)Lcom/codeborne/selenide/ElementsCo" +
            "llection;")]
        public virtual global::com.codeborne.selenide.ElementsCollection shouldBe(global::com.codeborne.selenide.CollectionCondition[] par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.ElementsCollection.j4n_shouldBe5, global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/ElementsCollection;")]
        public virtual global::com.codeborne.selenide.ElementsCollection filterBy(global::com.codeborne.selenide.Condition par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.ElementsCollection.j4n_filterBy6, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/ElementsCollection;")]
        public virtual global::com.codeborne.selenide.ElementsCollection exclude(global::com.codeborne.selenide.Condition par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.ElementsCollection.j4n_exclude7, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/ElementsCollection;")]
        public virtual global::com.codeborne.selenide.ElementsCollection excludeWith(global::com.codeborne.selenide.Condition par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.ElementsCollection.j4n_excludeWith8, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/SelenideElement;")]
        public virtual global::com.codeborne.selenide.SelenideElement findBy(global::com.codeborne.selenide.Condition par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.ElementsCollection.j4n_findBy9, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/util/Collection;)[Ljava/lang/String;")]
        public static global::java.lang.String[] getTexts(global::java.util.Collection par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.ElementsCollection.staticClass, global::com.codeborne.selenide.ElementsCollection.j4n_getTexts10, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.Collection>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[Ljava/lang/String;")]
        public virtual global::java.lang.String[] getTexts() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.ElementsCollection.j4n_getTexts11));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/util/Collection;)Ljava/lang/String;")]
        public static global::java.lang.String elementsToString(global::java.util.Collection par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.ElementsCollection.staticClass, global::com.codeborne.selenide.ElementsCollection.j4n_elementsToString12, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.Collection>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)Lcom/codeborne/selenide/ElementsCollection;")]
        public virtual global::com.codeborne.selenide.ElementsCollection shouldHaveSize(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.ElementsCollection.j4n_shouldHaveSize13, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.ElementsCollection(@__env);
            }
        }
    }
    #endregion
}
