//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class Selenide : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_sleep0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_close1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_open2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_open3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_open4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_open5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_actions6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_selectRadio7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_S8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_S9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_S10;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_S11;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_S12;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_S13;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_S14;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_S15;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_SS16;

        internal static global::net.sf.jni4net.jni.MethodId j4n_SS17;

        internal static global::net.sf.jni4net.jni.MethodId j4n_SS18;

        internal static global::net.sf.jni4net.jni.MethodId j4n_SS19;

        internal static global::net.sf.jni4net.jni.MethodId j4n_SS20;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_screenshot21;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getJavascriptErrors22;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_executeJavaScript23;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_switchTo24;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_title25;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getFocusedElement26;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getSelectedRadio27;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_onConfirmReturn28;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_assertNoJavascriptErrors29;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getWebDriverLogs30;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getWebDriverLogs31;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getElement32;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getElement33;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_updateHash34;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_refresh35;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_back36;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_forward37;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getElements38;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_confirm39;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_confirm40;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_dismiss41;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_dismiss42;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_page43;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_page44;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_Wait45;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_zoom46;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_navigator47;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorSelenide48;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public Selenide() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n__ctorSelenide48, this);
            }
        }
        
        protected Selenide(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.Selenide.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/impl/Navigator;")]
        public static global::com.codeborne.selenide.impl.Navigator navigator {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.impl.Navigator>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_navigator47));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.Selenide.staticClass = @__class;
            global::com.codeborne.selenide.Selenide.j4n_sleep0 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "sleep", "(J)V");
            global::com.codeborne.selenide.Selenide.j4n_close1 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "close", "()V");
            global::com.codeborne.selenide.Selenide.j4n_open2 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "open", "(Ljava/net/URL;Ljava/lang/Class;)Ljava/lang/Object;");
            global::com.codeborne.selenide.Selenide.j4n_open3 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "open", "(Ljava/lang/String;)V");
            global::com.codeborne.selenide.Selenide.j4n_open4 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "open", "(Ljava/net/URL;)V");
            global::com.codeborne.selenide.Selenide.j4n_open5 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "open", "(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;");
            global::com.codeborne.selenide.Selenide.j4n_actions6 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "actions", "()Lorg/openqa/selenium/interactions/Actions;");
            global::com.codeborne.selenide.Selenide.j4n_selectRadio7 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "selectRadio", "(Lorg/openqa/selenium/By;Ljava/lang/String;)Lcom/codeborne/selenide/SelenideEleme" +
                    "nt;");
            global::com.codeborne.selenide.Selenide.j4n_S8 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$", "(Lorg/openqa/selenium/By;I)Lcom/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.Selenide.j4n_S9 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$", "(Lorg/openqa/selenium/WebElement;Ljava/lang/String;)Lcom/codeborne/selenide/Selen" +
                    "ideElement;");
            global::com.codeborne.selenide.Selenide.j4n_S10 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$", "(Lorg/openqa/selenium/By;)Lcom/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.Selenide.j4n_S11 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$", "(Lorg/openqa/selenium/WebElement;Lorg/openqa/selenium/By;I)Lcom/codeborne/selenid" +
                    "e/SelenideElement;");
            global::com.codeborne.selenide.Selenide.j4n_S12 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$", "(Lorg/openqa/selenium/WebElement;Lorg/openqa/selenium/By;)Lcom/codeborne/selenide" +
                    "/SelenideElement;");
            global::com.codeborne.selenide.Selenide.j4n_S13 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$", "(Lorg/openqa/selenium/WebElement;Ljava/lang/String;I)Lcom/codeborne/selenide/Sele" +
                    "nideElement;");
            global::com.codeborne.selenide.Selenide.j4n_S14 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$", "(Ljava/lang/String;I)Lcom/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.Selenide.j4n_S15 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$", "(Ljava/lang/String;)Lcom/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.Selenide.j4n_SS16 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$$", "(Lorg/openqa/selenium/WebElement;Ljava/lang/String;)Lcom/codeborne/selenide/Eleme" +
                    "ntsCollection;");
            global::com.codeborne.selenide.Selenide.j4n_SS17 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$$", "(Lorg/openqa/selenium/By;)Lcom/codeborne/selenide/ElementsCollection;");
            global::com.codeborne.selenide.Selenide.j4n_SS18 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$$", "(Lorg/openqa/selenium/WebElement;Lorg/openqa/selenium/By;)Lcom/codeborne/selenide" +
                    "/ElementsCollection;");
            global::com.codeborne.selenide.Selenide.j4n_SS19 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$$", "(Ljava/lang/String;)Lcom/codeborne/selenide/ElementsCollection;");
            global::com.codeborne.selenide.Selenide.j4n_SS20 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "$$", "(Ljava/util/Collection;)Lcom/codeborne/selenide/ElementsCollection;");
            global::com.codeborne.selenide.Selenide.j4n_screenshot21 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "screenshot", "(Ljava/lang/String;)Ljava/lang/String;");
            global::com.codeborne.selenide.Selenide.j4n_getJavascriptErrors22 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "getJavascriptErrors", "()Ljava/util/List;");
            global::com.codeborne.selenide.Selenide.j4n_executeJavaScript23 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "executeJavaScript", "(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;");
            global::com.codeborne.selenide.Selenide.j4n_switchTo24 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "switchTo", "()Lcom/codeborne/selenide/SelenideTargetLocator;");
            global::com.codeborne.selenide.Selenide.j4n_title25 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "title", "()Ljava/lang/String;");
            global::com.codeborne.selenide.Selenide.j4n_getFocusedElement26 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "getFocusedElement", "()Lorg/openqa/selenium/WebElement;");
            global::com.codeborne.selenide.Selenide.j4n_getSelectedRadio27 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "getSelectedRadio", "(Lorg/openqa/selenium/By;)Lcom/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.Selenide.j4n_onConfirmReturn28 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "onConfirmReturn", "(Z)V");
            global::com.codeborne.selenide.Selenide.j4n_assertNoJavascriptErrors29 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "assertNoJavascriptErrors", "()V");
            global::com.codeborne.selenide.Selenide.j4n_getWebDriverLogs30 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "getWebDriverLogs", "(Ljava/lang/String;Ljava/util/logging/Level;)Ljava/util/List;");
            global::com.codeborne.selenide.Selenide.j4n_getWebDriverLogs31 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "getWebDriverLogs", "(Ljava/lang/String;)Ljava/util/List;");
            global::com.codeborne.selenide.Selenide.j4n_getElement32 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "getElement", "(Lorg/openqa/selenium/By;)Lcom/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.Selenide.j4n_getElement33 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "getElement", "(Lorg/openqa/selenium/By;I)Lcom/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.Selenide.j4n_updateHash34 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "updateHash", "(Ljava/lang/String;)V");
            global::com.codeborne.selenide.Selenide.j4n_refresh35 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "refresh", "()V");
            global::com.codeborne.selenide.Selenide.j4n_back36 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "back", "()V");
            global::com.codeborne.selenide.Selenide.j4n_forward37 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "forward", "()V");
            global::com.codeborne.selenide.Selenide.j4n_getElements38 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "getElements", "(Lorg/openqa/selenium/By;)Lcom/codeborne/selenide/ElementsCollection;");
            global::com.codeborne.selenide.Selenide.j4n_confirm39 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "confirm", "(Ljava/lang/String;)Ljava/lang/String;");
            global::com.codeborne.selenide.Selenide.j4n_confirm40 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "confirm", "()Ljava/lang/String;");
            global::com.codeborne.selenide.Selenide.j4n_dismiss41 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "dismiss", "(Ljava/lang/String;)Ljava/lang/String;");
            global::com.codeborne.selenide.Selenide.j4n_dismiss42 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "dismiss", "()Ljava/lang/String;");
            global::com.codeborne.selenide.Selenide.j4n_page43 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "page", "(Ljava/lang/Class;)Ljava/lang/Object;");
            global::com.codeborne.selenide.Selenide.j4n_page44 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "page", "(Ljava/lang/Object;)Ljava/lang/Object;");
            global::com.codeborne.selenide.Selenide.j4n_Wait45 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "Wait", "()Lorg/openqa/selenium/support/ui/FluentWait;");
            global::com.codeborne.selenide.Selenide.j4n_zoom46 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Selenide.staticClass, "zoom", "(D)V");
            global::com.codeborne.selenide.Selenide.j4n_navigator47 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Selenide.staticClass, "navigator", "Lcom/codeborne/selenide/impl/Navigator;");
            global::com.codeborne.selenide.Selenide.j4n__ctorSelenide48 = @__env.GetMethodID(global::com.codeborne.selenide.Selenide.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(J)V")]
        public static void sleep(long par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_sleep0, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public static void close() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_close1);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/net/URL;Ljava/lang/Class;)Ljava/lang/Object;")]
        public static global::java.lang.Object open(global::java.net.URL par0, global::java.lang.Class par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_open2, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)V")]
        public static void open(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_open3, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/net/URL;)V")]
        public static void open(global::java.net.URL par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_open4, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;")]
        public static global::java.lang.Object open(global::java.lang.String par0, global::java.lang.Class par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_open5, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/openqa/selenium/interactions/Actions;")]
        public static global::java.lang.Object actions() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_actions6));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/By;Ljava/lang/String;)Lcom/codeborne/selenide/SelenideEleme" +
            "nt;")]
        public static global::com.codeborne.selenide.SelenideElement selectRadio(global::java.lang.Object par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_selectRadio7, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/By;I)Lcom/codeborne/selenide/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement S(global::java.lang.Object par0, int par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_S8, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebElement;Ljava/lang/String;)Lcom/codeborne/selenide/Selen" +
            "ideElement;")]
        public static global::com.codeborne.selenide.SelenideElement S(global::java.lang.Object par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_S9, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/By;)Lcom/codeborne/selenide/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement S(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_S10, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebElement;Lorg/openqa/selenium/By;I)Lcom/codeborne/selenid" +
            "e/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement S(global::java.lang.Object par0, global::java.lang.Object par1, int par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_S11, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebElement;Lorg/openqa/selenium/By;)Lcom/codeborne/selenide" +
            "/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement S(global::java.lang.Object par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_S12, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebElement;Ljava/lang/String;I)Lcom/codeborne/selenide/Sele" +
            "nideElement;")]
        public static global::com.codeborne.selenide.SelenideElement S(global::java.lang.Object par0, global::java.lang.String par1, int par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_S13, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;I)Lcom/codeborne/selenide/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement S(global::java.lang.String par0, int par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_S14, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement S(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_S15, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebElement;Ljava/lang/String;)Lcom/codeborne/selenide/Eleme" +
            "ntsCollection;")]
        public static global::com.codeborne.selenide.ElementsCollection SS(global::java.lang.Object par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_SS16, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/By;)Lcom/codeborne/selenide/ElementsCollection;")]
        public static global::com.codeborne.selenide.ElementsCollection SS(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_SS17, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebElement;Lorg/openqa/selenium/By;)Lcom/codeborne/selenide" +
            "/ElementsCollection;")]
        public static global::com.codeborne.selenide.ElementsCollection SS(global::java.lang.Object par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_SS18, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/ElementsCollection;")]
        public static global::com.codeborne.selenide.ElementsCollection SS(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_SS19, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/util/Collection;)Lcom/codeborne/selenide/ElementsCollection;")]
        public static global::com.codeborne.selenide.ElementsCollection SS(global::java.util.Collection par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_SS20, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.Collection>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Ljava/lang/String;")]
        public static global::java.lang.String screenshot(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_screenshot21, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/List;")]
        public static global::java.util.List getJavascriptErrors() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.List>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_getJavascriptErrors22));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;")]
        public static global::java.lang.Object executeJavaScript(global::java.lang.String par0, global::java.lang.Object[] par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_executeJavaScript23, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParArrayFullC2J<global::java.lang.Object[], global::java.lang.Object>(@__env, par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/codeborne/selenide/SelenideTargetLocator;")]
        public static global::com.codeborne.selenide.SelenideTargetLocator switchTo() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.SelenideTargetLocator>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_switchTo24));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public static global::java.lang.String title() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_title25));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/openqa/selenium/WebElement;")]
        public static global::java.lang.Object getFocusedElement() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_getFocusedElement26));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/By;)Lcom/codeborne/selenide/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement getSelectedRadio(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_getSelectedRadio27, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Z)V")]
        public static void onConfirmReturn(bool par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_onConfirmReturn28, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public static void assertNoJavascriptErrors() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_assertNoJavascriptErrors29);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/util/logging/Level;)Ljava/util/List;")]
        public static global::java.util.List getWebDriverLogs(global::java.lang.String par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.List>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_getWebDriverLogs30, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Ljava/util/List;")]
        public static global::java.util.List getWebDriverLogs(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.List>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_getWebDriverLogs31, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/By;)Lcom/codeborne/selenide/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement getElement(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_getElement32, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/By;I)Lcom/codeborne/selenide/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement getElement(global::java.lang.Object par0, int par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_getElement33, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)V")]
        public static void updateHash(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_updateHash34, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public static void refresh() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_refresh35);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public static void back() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_back36);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public static void forward() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_forward37);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/By;)Lcom/codeborne/selenide/ElementsCollection;")]
        public static global::com.codeborne.selenide.ElementsCollection getElements(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ElementsCollection>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_getElements38, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Ljava/lang/String;")]
        public static global::java.lang.String confirm(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_confirm39, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public static global::java.lang.String confirm() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_confirm40));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Ljava/lang/String;")]
        public static global::java.lang.String dismiss(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_dismiss41, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public static global::java.lang.String dismiss() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_dismiss42));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Class;)Ljava/lang/Object;")]
        public static global::java.lang.Object page(global::java.lang.Class par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_page43, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Object;)Ljava/lang/Object;")]
        public static global::java.lang.Object page(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_page44, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/openqa/selenium/support/ui/FluentWait;")]
        public static global::java.lang.Object Wait() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_Wait45));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(D)V")]
        public static void zoom(double par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.Selenide.staticClass, global::com.codeborne.selenide.Selenide.j4n_zoom46, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.Selenide(@__env);
            }
        }
    }
    #endregion
}
