// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package com.codeborne.selenide.impl;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class WebDriverContainer_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return com.codeborne.selenide.impl.WebDriverContainer_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        com.codeborne.selenide.impl.WebDriverContainer_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __WebDriverContainer extends system.Object implements com.codeborne.selenide.impl.WebDriverContainer {
    
    protected __WebDriverContainer(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)V")
    public native void addListener(org.openqa.selenium.support.events.WebDriverEventListener par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void closeWebDriver();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String getPageSource();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String getCurrentUrl();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)Ljava/lang/Object;")
    public native org.openqa.selenium.WebDriver setWebDriver(org.openqa.selenium.WebDriver par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)V")
    public native void setProxy(org.openqa.selenium.Proxy par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/Object;")
    public native org.openqa.selenium.WebDriver getWebDriver();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/Object;")
    public native org.openqa.selenium.WebDriver getAndCheckWebDriver();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean hasWebDriverStarted();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void clearBrowserCache();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String getCurrentFrameUrl();
}
//</generated-proxy>
