// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package com.codeborne.selenide.logevents;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class LogEvent_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return com.codeborne.selenide.logevents.LogEvent_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        com.codeborne.selenide.logevents.LogEvent_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __LogEvent extends system.Object implements com.codeborne.selenide.logevents.LogEvent {
    
    protected __LogEvent(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/Throwable;")
    public native java.lang.Throwable getError();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/Object;")
    public native com.codeborne.selenide.logevents.LogEvent$EventStatus getStatus();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String getSubject();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String getElement();
    
    @net.sf.jni4net.attributes.ClrMethod("()J")
    public native long getDuration();
}
//</generated-proxy>
