//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.logevents {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface LogEvent {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/Throwable;")]
        global::java.lang.Throwable getError();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/codeborne/selenide/logevents/LogEvent$EventStatus;")]
        global::java.lang.Object getStatus();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        global::java.lang.String getSubject();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        global::java.lang.String getElement();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        long getDuration();
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class LogEvent_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.logevents.@__LogEvent.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::com.codeborne.selenide.logevents.LogEvent), typeof(global::com.codeborne.selenide.logevents.LogEvent_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::com.codeborne.selenide.logevents.LogEvent), typeof(global::com.codeborne.selenide.logevents.LogEvent_))]
    internal sealed partial class @__LogEvent : global::java.lang.Object, global::com.codeborne.selenide.logevents.LogEvent {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getError0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getStatus1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getSubject2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getElement3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getDuration4;
        
        private @__LogEvent(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.logevents.@__LogEvent.staticClass = @__class;
            global::com.codeborne.selenide.logevents.@__LogEvent.j4n_getError0 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.@__LogEvent.staticClass, "getError", "()Ljava/lang/Throwable;");
            global::com.codeborne.selenide.logevents.@__LogEvent.j4n_getStatus1 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.@__LogEvent.staticClass, "getStatus", "()Lcom/codeborne/selenide/logevents/LogEvent$EventStatus;");
            global::com.codeborne.selenide.logevents.@__LogEvent.j4n_getSubject2 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.@__LogEvent.staticClass, "getSubject", "()Ljava/lang/String;");
            global::com.codeborne.selenide.logevents.@__LogEvent.j4n_getElement3 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.@__LogEvent.staticClass, "getElement", "()Ljava/lang/String;");
            global::com.codeborne.selenide.logevents.@__LogEvent.j4n_getDuration4 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.@__LogEvent.staticClass, "getDuration", "()J");
        }
        
        public global::java.lang.Throwable getError() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Throwable>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.logevents.@__LogEvent.j4n_getError0));
            }
        }
        
        public global::java.lang.Object getStatus() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.logevents.@__LogEvent.j4n_getStatus1));
            }
        }
        
        public global::java.lang.String getSubject() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.logevents.@__LogEvent.j4n_getSubject2));
            }
        }
        
        public global::java.lang.String getElement() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.logevents.@__LogEvent.j4n_getElement3));
            }
        }
        
        public long getDuration() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::com.codeborne.selenide.logevents.@__LogEvent.j4n_getDuration4)));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__LogEvent);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getError", "getError0", "()Ljava/lang/Throwable;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getStatus", "getStatus1", "()Lcom/codeborne/selenide/logevents/LogEvent$EventStatus;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getSubject", "getSubject2", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getElement", "getElement3", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getDuration", "getDuration4", "()J"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getError0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/Throwable;
            // ()Ljava/lang/Throwable;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::com.codeborne.selenide.logevents.LogEvent @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.logevents.LogEvent>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.lang.Throwable>(@__env, @__real.getError());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getStatus1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lcom/codeborne/selenide/logevents/LogEvent$EventStatus;
            // ()Ljava/lang/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::com.codeborne.selenide.logevents.LogEvent @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.logevents.LogEvent>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getStatus());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getSubject2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::com.codeborne.selenide.logevents.LogEvent @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.logevents.LogEvent>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getSubject());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getElement3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::com.codeborne.selenide.logevents.LogEvent @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.logevents.LogEvent>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getElement());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static long getDuration4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()J
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            long @__return = default(long);
            try {
            global::com.codeborne.selenide.logevents.LogEvent @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.logevents.LogEvent>(@__env, @__obj);
            @__return = ((long)(@__real.getDuration()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.logevents.@__LogEvent(@__env);
            }
        }
    }
    #endregion
}
