// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package com.codeborne.selenide;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class SelenideElement_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return com.codeborne.selenide.SelenideElement_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        com.codeborne.selenide.SelenideElement_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __SelenideElement extends system.Object implements com.codeborne.selenide.SelenideElement {
    
    protected __SelenideElement(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)Ljava/util/List;")
    public native java.util.List findElements(org.openqa.selenium.By par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)Ljava/lang/Object;")
    public native org.openqa.selenium.WebElement findElement(org.openqa.selenium.By par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)Ljava/lang/Object;")
    public native java.lang.Object getScreenshotAs(org.openqa.selenium.OutputType par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void clear();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/Object;")
    public native org.openqa.selenium.Point getLocation();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/Object;")
    public native org.openqa.selenium.Dimension getSize();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/String;")
    public native java.lang.String getAttribute(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void submit();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isDisplayed();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void click();
    
    @net.sf.jni4net.attributes.ClrMethod("([Ljava/lang/CharSequence;)V")
    public native void sendKeys(java.lang.CharSequence[] par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String getTagName();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isSelected();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/String;")
    public native java.lang.String getCssValue(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String getText();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isEnabled();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/Object;")
    public native org.openqa.selenium.WebElement findElementByLinkText(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/util/List;")
    public native java.util.List findElementsByLinkText(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/Object;")
    public native org.openqa.selenium.WebElement findElementByPartialLinkText(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/util/List;")
    public native java.util.List findElementsByPartialLinkText(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/Object;")
    public native org.openqa.selenium.WebElement findElementById(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/util/List;")
    public native java.util.List findElementsById(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/Object;")
    public native org.openqa.selenium.WebElement findElementByName(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/util/List;")
    public native java.util.List findElementsByName(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/Object;")
    public native org.openqa.selenium.WebElement findElementByTagName(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/util/List;")
    public native java.util.List findElementsByTagName(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/Object;")
    public native org.openqa.selenium.WebElement findElementByClassName(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/util/List;")
    public native java.util.List findElementsByClassName(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/Object;")
    public native org.openqa.selenium.WebElement findElementByCssSelector(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/util/List;")
    public native java.util.List findElementsByCssSelector(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/Object;")
    public native org.openqa.selenium.WebElement findElementByXPath(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/util/List;")
    public native java.util.List findElementsByXPath(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/Object;")
    public native org.openqa.selenium.WebDriver getWrappedDriver();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/Object;")
    public native org.openqa.selenium.WebElement getWrappedElement();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/Object;")
    public native org.openqa.selenium.interactions.internal.Coordinates getCoordinates();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String name();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement parent();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String toString();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement append(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;I)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement find(org.openqa.selenium.By par0, int par1);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement find(org.openqa.selenium.By par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement find(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;I)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement find(java.lang.String par0, int par1);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean exists();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement setValue(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String val();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement val(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/String;")
    public native java.lang.String attr(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lcom/codeborne/selenide/Condition;)Z")
    public native boolean is(com.codeborne.selenide.Condition par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void followLink();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement pressEnter();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement pressTab();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement pressEscape();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String innerText();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String innerHtml();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement selectRadio(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Ljava/lang/String;")
    public native java.lang.String data(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lcom/codeborne/selenide/Condition;)Z")
    public native boolean has(com.codeborne.selenide.Condition par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Z)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement setSelected(boolean par0);
    
    @net.sf.jni4net.attributes.ClrMethod("([Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement should(com.codeborne.selenide.Condition[] par0);
    
    @net.sf.jni4net.attributes.ClrMethod("([Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement shouldHave(com.codeborne.selenide.Condition[] par0);
    
    @net.sf.jni4net.attributes.ClrMethod("([Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement shouldBe(com.codeborne.selenide.Condition[] par0);
    
    @net.sf.jni4net.attributes.ClrMethod("([Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement shouldNot(com.codeborne.selenide.Condition[] par0);
    
    @net.sf.jni4net.attributes.ClrMethod("([Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement shouldNotHave(com.codeborne.selenide.Condition[] par0);
    
    @net.sf.jni4net.attributes.ClrMethod("([Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement shouldNotBe(com.codeborne.selenide.Condition[] par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lcom/codeborne/selenide/Condition;J)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement waitUntil(com.codeborne.selenide.Condition par0, long par1);
    
    @net.sf.jni4net.attributes.ClrMethod("(Lcom/codeborne/selenide/Condition;J)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement waitWhile(com.codeborne.selenide.Condition par0, long par1);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement closest(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;I)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement $(java.lang.String par0, int par1);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement $(org.openqa.selenium.By par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;I)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement $(org.openqa.selenium.By par0, int par1);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement $(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lcom/codeborne/selenide/ElementsCollection;")
    public native com.codeborne.selenide.ElementsCollection findAll(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)Lcom/codeborne/selenide/ElementsCollection;")
    public native com.codeborne.selenide.ElementsCollection findAll(org.openqa.selenium.By par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lcom/codeborne/selenide/ElementsCollection;")
    public native com.codeborne.selenide.ElementsCollection $$(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/Object;)Lcom/codeborne/selenide/ElementsCollection;")
    public native com.codeborne.selenide.ElementsCollection $$(org.openqa.selenium.By par0);
    
    @net.sf.jni4net.attributes.ClrMethod("([Ljava/io/File;)Ljava/io/File;")
    public native java.io.File uploadFile(java.io.File[] par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)V")
    public native void selectOption(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement scrollTo();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/io/File;")
    public native java.io.File download();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/Object;")
    public native org.openqa.selenium.WebElement toWebElement();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement contextClick();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement doubleClick();
    
    @net.sf.jni4net.attributes.ClrMethod("()Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement hover();
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement dragAndDropTo(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isImage();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String text();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/io/File;")
    public native java.io.File screenshot();
    
    @net.sf.jni4net.attributes.ClrMethod("([Ljava/lang/String;)Ljava/io/File;")
    public native java.io.File uploadFromClasspath(java.lang.String[] par0);
    
    @net.sf.jni4net.attributes.ClrMethod("(Ljava/lang/String;)V")
    public native void selectOptionByValue(java.lang.String par0);
    
    @net.sf.jni4net.attributes.ClrMethod("()Lcom/codeborne/selenide/SelenideElement;")
    public native com.codeborne.selenide.SelenideElement getSelectedOption();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String getSelectedValue();
    
    @net.sf.jni4net.attributes.ClrMethod("()Ljava/lang/String;")
    public native java.lang.String getSelectedText();
}
//</generated-proxy>
