//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.logevents {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class ErrorsCollector : global::java.lang.Object, global::com.codeborne.selenide.logevents.LogEventListener {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_onEvent0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_clear1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_failIfErrors2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorErrorsCollector3;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public ErrorsCollector() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.codeborne.selenide.logevents.ErrorsCollector.staticClass, global::com.codeborne.selenide.logevents.ErrorsCollector.j4n__ctorErrorsCollector3, this);
            }
        }
        
        protected ErrorsCollector(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.logevents.ErrorsCollector.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.logevents.ErrorsCollector.staticClass = @__class;
            global::com.codeborne.selenide.logevents.ErrorsCollector.j4n_onEvent0 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.ErrorsCollector.staticClass, "onEvent", "(Lcom/codeborne/selenide/logevents/LogEvent;)V");
            global::com.codeborne.selenide.logevents.ErrorsCollector.j4n_clear1 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.ErrorsCollector.staticClass, "clear", "()V");
            global::com.codeborne.selenide.logevents.ErrorsCollector.j4n_failIfErrors2 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.ErrorsCollector.staticClass, "failIfErrors", "(Ljava/lang/String;)V");
            global::com.codeborne.selenide.logevents.ErrorsCollector.j4n__ctorErrorsCollector3 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.ErrorsCollector.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/logevents/LogEvent;)V")]
        public virtual void onEvent(global::com.codeborne.selenide.logevents.LogEvent par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.logevents.ErrorsCollector.j4n_onEvent0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::com.codeborne.selenide.logevents.LogEvent>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void clear() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.logevents.ErrorsCollector.j4n_clear1);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)V")]
        public virtual void failIfErrors(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.logevents.ErrorsCollector.j4n_failIfErrors2, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.logevents.ErrorsCollector(@__env);
            }
        }
    }
    #endregion
}
