//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.logevents {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class SelenideLog : global::java.lang.Object, global::com.codeborne.selenide.logevents.LogEvent {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getError0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getStatus1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getSubject2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getElement3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getDuration4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setError5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorSelenideLog6;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;)V")]
        public SelenideLog(global::java.lang.String par0, global::java.lang.String par1) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.NewObject(global::com.codeborne.selenide.logevents.SelenideLog.staticClass, global::com.codeborne.selenide.logevents.SelenideLog.j4n__ctorSelenideLog6, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1));
            }
        }
        
        protected SelenideLog(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.logevents.SelenideLog.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.logevents.SelenideLog.staticClass = @__class;
            global::com.codeborne.selenide.logevents.SelenideLog.j4n_getError0 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.SelenideLog.staticClass, "getError", "()Ljava/lang/Throwable;");
            global::com.codeborne.selenide.logevents.SelenideLog.j4n_getStatus1 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.SelenideLog.staticClass, "getStatus", "()Lcom/codeborne/selenide/logevents/LogEvent$EventStatus;");
            global::com.codeborne.selenide.logevents.SelenideLog.j4n_getSubject2 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.SelenideLog.staticClass, "getSubject", "()Ljava/lang/String;");
            global::com.codeborne.selenide.logevents.SelenideLog.j4n_getElement3 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.SelenideLog.staticClass, "getElement", "()Ljava/lang/String;");
            global::com.codeborne.selenide.logevents.SelenideLog.j4n_getDuration4 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.SelenideLog.staticClass, "getDuration", "()J");
            global::com.codeborne.selenide.logevents.SelenideLog.j4n_setError5 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.SelenideLog.staticClass, "setError", "(Ljava/lang/Throwable;)V");
            global::com.codeborne.selenide.logevents.SelenideLog.j4n__ctorSelenideLog6 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.SelenideLog.staticClass, "<init>", "(Ljava/lang/String;Ljava/lang/String;)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/Throwable;")]
        public virtual global::java.lang.Throwable getError() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Throwable>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.logevents.SelenideLog.j4n_getError0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/codeborne/selenide/logevents/LogEvent$EventStatus;")]
        public virtual global::java.lang.Object getStatus() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.logevents.SelenideLog.j4n_getStatus1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getSubject() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.logevents.SelenideLog.j4n_getSubject2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getElement() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.logevents.SelenideLog.j4n_getElement3));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        public virtual long getDuration() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::com.codeborne.selenide.logevents.SelenideLog.j4n_getDuration4)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Throwable;)V")]
        public virtual void setError(global::java.lang.Throwable par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.logevents.SelenideLog.j4n_setError5, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Throwable>(@__env, par0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.logevents.SelenideLog(@__env);
            }
        }
    }
    #endregion
}
