//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.logevents {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class SimpleReport : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_start0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_finish1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorSimpleReport2;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public SimpleReport() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.codeborne.selenide.logevents.SimpleReport.staticClass, global::com.codeborne.selenide.logevents.SimpleReport.j4n__ctorSimpleReport2, this);
            }
        }
        
        protected SimpleReport(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.logevents.SimpleReport.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.logevents.SimpleReport.staticClass = @__class;
            global::com.codeborne.selenide.logevents.SimpleReport.j4n_start0 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.SimpleReport.staticClass, "start", "()V");
            global::com.codeborne.selenide.logevents.SimpleReport.j4n_finish1 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.SimpleReport.staticClass, "finish", "(Ljava/lang/String;)V");
            global::com.codeborne.selenide.logevents.SimpleReport.j4n__ctorSimpleReport2 = @__env.GetMethodID(global::com.codeborne.selenide.logevents.SimpleReport.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void start() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.logevents.SimpleReport.j4n_start0);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)V")]
        public virtual void finish(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.logevents.SimpleReport.j4n_finish1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.logevents.SimpleReport(@__env);
            }
        }
    }
    #endregion
}
