//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class Condition : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_apply0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_name1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_type2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_value3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_id4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_and5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_or6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_be7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_have8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_not9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_text10;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_hasAttribute11;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_attribute12;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_attribute13;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_exactValue14;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_matchesText15;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_matchText16;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_hasText17;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_exactText18;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_hasClass19;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_hasClass20;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_cssClass21;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_actualValue22;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_because23;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_textCaseSensitive24;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_exactTextCaseSensitive25;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_applyNull26;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_hasValue27;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_visible28;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_exist29;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_present30;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_hidden31;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_appear32;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_appears33;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_disappears34;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_disappear35;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_readonly36;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_empty37;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_focused38;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_enabled39;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_disabled40;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_selected41;
        
        protected Condition(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.Condition.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition visible {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_visible28));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition exist {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_exist29));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition present {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_present30));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition hidden {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_hidden31));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition appear {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_appear32));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition appears {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_appears33));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition disappears {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_disappears34));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition disappear {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_disappear35));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition @readonly {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_readonly36));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition empty {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_empty37));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition focused {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_focused38));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition enabled {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_enabled39));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition disabled {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_disabled40));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition selected {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_selected41));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.Condition.staticClass = @__class;
            global::com.codeborne.selenide.Condition.j4n_apply0 = @__env.GetMethodID(global::com.codeborne.selenide.Condition.staticClass, "apply", "(Ljava/lang/Object;)Z");
            global::com.codeborne.selenide.Condition.j4n_name1 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "name", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_type2 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "type", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_value3 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "value", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_id4 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "id", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_and5 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "and", "(Ljava/lang/String;[Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/Co" +
                    "ndition;");
            global::com.codeborne.selenide.Condition.j4n_or6 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "or", "(Ljava/lang/String;[Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/Co" +
                    "ndition;");
            global::com.codeborne.selenide.Condition.j4n_be7 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "be", "(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_have8 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "have", "(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_not9 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "not", "(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_text10 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "text", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_hasAttribute11 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "hasAttribute", "(Ljava/lang/String;Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_attribute12 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "attribute", "(Ljava/lang/String;Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_attribute13 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "attribute", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_exactValue14 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "exactValue", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_matchesText15 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "matchesText", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_matchText16 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "matchText", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_hasText17 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "hasText", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_exactText18 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "exactText", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_hasClass19 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "hasClass", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_hasClass20 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "hasClass", "(Lorg/openqa/selenium/WebElement;Ljava/lang/String;)Z");
            global::com.codeborne.selenide.Condition.j4n_cssClass21 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "cssClass", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_actualValue22 = @__env.GetMethodID(global::com.codeborne.selenide.Condition.staticClass, "actualValue", "(Lorg/openqa/selenium/WebElement;)Ljava/lang/String;");
            global::com.codeborne.selenide.Condition.j4n_because23 = @__env.GetMethodID(global::com.codeborne.selenide.Condition.staticClass, "because", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_textCaseSensitive24 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "textCaseSensitive", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_exactTextCaseSensitive25 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "exactTextCaseSensitive", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_applyNull26 = @__env.GetMethodID(global::com.codeborne.selenide.Condition.staticClass, "applyNull", "()Z");
            global::com.codeborne.selenide.Condition.j4n_hasValue27 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Condition.staticClass, "hasValue", "(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_visible28 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "visible", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_exist29 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "exist", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_present30 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "present", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_hidden31 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "hidden", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_appear32 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "appear", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_appears33 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "appears", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_disappears34 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "disappears", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_disappear35 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "disappear", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_readonly36 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "readonly", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_empty37 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "empty", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_focused38 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "focused", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_enabled39 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "enabled", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_disabled40 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "disabled", "Lcom/codeborne/selenide/Condition;");
            global::com.codeborne.selenide.Condition.j4n_selected41 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Condition.staticClass, "selected", "Lcom/codeborne/selenide/Condition;");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Object;)Z")]
        public virtual bool apply(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.codeborne.selenide.Condition.j4n_apply0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition name(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_name1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition type(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_type2, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition value(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_value3, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition id(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_id4, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;[Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/Co" +
            "ndition;")]
        public static global::com.codeborne.selenide.Condition and(global::java.lang.String par0, global::com.codeborne.selenide.Condition[] par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_and5, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;[Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/Co" +
            "ndition;")]
        public static global::com.codeborne.selenide.Condition or(global::java.lang.String par0, global::com.codeborne.selenide.Condition[] par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_or6, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition be(global::com.codeborne.selenide.Condition par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_be7, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition have(global::com.codeborne.selenide.Condition par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_have8, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/Condition;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition not(global::com.codeborne.selenide.Condition par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_not9, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition text(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_text10, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition hasAttribute(global::java.lang.String par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_hasAttribute11, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition attribute(global::java.lang.String par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_attribute12, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition attribute(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_attribute13, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition exactValue(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_exactValue14, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition matchesText(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_matchesText15, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition matchText(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_matchText16, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition hasText(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_hasText17, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition exactText(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_exactText18, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition hasClass(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_hasClass19, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebElement;Ljava/lang/String;)Z")]
        public static bool hasClass(global::java.lang.Object par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_hasClass20, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition cssClass(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_cssClass21, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebElement;)Ljava/lang/String;")]
        public virtual global::java.lang.String actualValue(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.Condition.j4n_actualValue22, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public virtual global::com.codeborne.selenide.Condition because(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.Condition.j4n_because23, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition textCaseSensitive(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_textCaseSensitive24, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition exactTextCaseSensitive(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_exactTextCaseSensitive25, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public bool applyNull() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.codeborne.selenide.Condition.j4n_applyNull26)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/codeborne/selenide/Condition;")]
        public static global::com.codeborne.selenide.Condition hasValue(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.Condition>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Condition.staticClass, global::com.codeborne.selenide.Condition.j4n_hasValue27, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.Condition(@__env);
            }
        }
    }
    #endregion
}
