//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class Screenshots : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_startContext0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_finishContext1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getLastScreenshot2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_takeScreenShot3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_takeScreenShot4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_takeScreenShot5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_takeScreenShotAsFile6;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_screenshots7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorScreenshots8;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public Screenshots() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.codeborne.selenide.Screenshots.staticClass, global::com.codeborne.selenide.Screenshots.j4n__ctorScreenshots8, this);
            }
        }
        
        protected Screenshots(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.Screenshots.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/impl/ScreenShotLaboratory;")]
        public static global::com.codeborne.selenide.impl.ScreenShotLaboratory screenshots {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.impl.ScreenShotLaboratory>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.Screenshots.staticClass, global::com.codeborne.selenide.Screenshots.j4n_screenshots7));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.Screenshots.staticClass = @__class;
            global::com.codeborne.selenide.Screenshots.j4n_startContext0 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Screenshots.staticClass, "startContext", "(Ljava/lang/String;Ljava/lang/String;)V");
            global::com.codeborne.selenide.Screenshots.j4n_finishContext1 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Screenshots.staticClass, "finishContext", "()Ljava/util/List;");
            global::com.codeborne.selenide.Screenshots.j4n_getLastScreenshot2 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Screenshots.staticClass, "getLastScreenshot", "()Ljava/io/File;");
            global::com.codeborne.selenide.Screenshots.j4n_takeScreenShot3 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Screenshots.staticClass, "takeScreenShot", "(Lorg/openqa/selenium/WebElement;)Ljava/io/File;");
            global::com.codeborne.selenide.Screenshots.j4n_takeScreenShot4 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Screenshots.staticClass, "takeScreenShot", "(Ljava/lang/String;)Ljava/lang/String;");
            global::com.codeborne.selenide.Screenshots.j4n_takeScreenShot5 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Screenshots.staticClass, "takeScreenShot", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;");
            global::com.codeborne.selenide.Screenshots.j4n_takeScreenShotAsFile6 = @__env.GetStaticMethodID(global::com.codeborne.selenide.Screenshots.staticClass, "takeScreenShotAsFile", "()Ljava/io/File;");
            global::com.codeborne.selenide.Screenshots.j4n_screenshots7 = @__env.GetStaticFieldID(global::com.codeborne.selenide.Screenshots.staticClass, "screenshots", "Lcom/codeborne/selenide/impl/ScreenShotLaboratory;");
            global::com.codeborne.selenide.Screenshots.j4n__ctorScreenshots8 = @__env.GetMethodID(global::com.codeborne.selenide.Screenshots.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;)V")]
        public static void startContext(global::java.lang.String par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.Screenshots.staticClass, global::com.codeborne.selenide.Screenshots.j4n_startContext0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/List;")]
        public static global::java.util.List finishContext() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.List>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Screenshots.staticClass, global::com.codeborne.selenide.Screenshots.j4n_finishContext1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/io/File;")]
        public static global::java.io.File getLastScreenshot() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.io.File>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Screenshots.staticClass, global::com.codeborne.selenide.Screenshots.j4n_getLastScreenshot2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebElement;)Ljava/io/File;")]
        public static global::java.io.File takeScreenShot(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.io.File>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Screenshots.staticClass, global::com.codeborne.selenide.Screenshots.j4n_takeScreenShot3, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Ljava/lang/String;")]
        public static global::java.lang.String takeScreenShot(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Screenshots.staticClass, global::com.codeborne.selenide.Screenshots.j4n_takeScreenShot4, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")]
        public static global::java.lang.String takeScreenShot(global::java.lang.String par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Screenshots.staticClass, global::com.codeborne.selenide.Screenshots.j4n_takeScreenShot5, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/io/File;")]
        public static global::java.io.File takeScreenShotAsFile() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.io.File>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.Screenshots.staticClass, global::com.codeborne.selenide.Screenshots.j4n_takeScreenShotAsFile6));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.Screenshots(@__env);
            }
        }
    }
    #endregion
}
