//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class WebDriverRunner : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_url0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isPhantomjs1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_addListener2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_closeWebDriver3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isOpera4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_source5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isIE6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isHtmlUnit7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setWebDriver8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setProxy9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getWebDriver10;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isHeadless11;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isSafari12;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isFirefox13;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isChrome14;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getAndCheckWebDriver15;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_hasWebDriverStarted16;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_supportsModalDialogs17;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_clearBrowserCache18;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_currentFrameUrl19;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_webdriverContainer20;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_CHROME21;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_INTERNET_EXPLORER22;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_FIREFOX23;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_SAFARI24;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_HTMLUNIT25;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PHANTOMJS26;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_OPERA27;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorWebDriverRunner28;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public WebDriverRunner() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n__ctorWebDriverRunner28, this);
            }
        }
        
        protected WebDriverRunner(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.WebDriverRunner.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/impl/WebDriverContainer;")]
        public static global::com.codeborne.selenide.impl.WebDriverContainer webdriverContainer {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.impl.WebDriverContainer>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_webdriverContainer20));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String CHROME {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_CHROME21));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String INTERNET_EXPLORER {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_INTERNET_EXPLORER22));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String FIREFOX {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_FIREFOX23));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String SAFARI {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_SAFARI24));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String HTMLUNIT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_HTMLUNIT25));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PHANTOMJS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_PHANTOMJS26));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String OPERA {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_OPERA27));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.WebDriverRunner.staticClass = @__class;
            global::com.codeborne.selenide.WebDriverRunner.j4n_url0 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "url", "()Ljava/lang/String;");
            global::com.codeborne.selenide.WebDriverRunner.j4n_isPhantomjs1 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "isPhantomjs", "()Z");
            global::com.codeborne.selenide.WebDriverRunner.j4n_addListener2 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "addListener", "(Lorg/openqa/selenium/support/events/WebDriverEventListener;)V");
            global::com.codeborne.selenide.WebDriverRunner.j4n_closeWebDriver3 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "closeWebDriver", "()V");
            global::com.codeborne.selenide.WebDriverRunner.j4n_isOpera4 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "isOpera", "()Z");
            global::com.codeborne.selenide.WebDriverRunner.j4n_source5 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "source", "()Ljava/lang/String;");
            global::com.codeborne.selenide.WebDriverRunner.j4n_isIE6 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "isIE", "()Z");
            global::com.codeborne.selenide.WebDriverRunner.j4n_isHtmlUnit7 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "isHtmlUnit", "()Z");
            global::com.codeborne.selenide.WebDriverRunner.j4n_setWebDriver8 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "setWebDriver", "(Lorg/openqa/selenium/WebDriver;)V");
            global::com.codeborne.selenide.WebDriverRunner.j4n_setProxy9 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "setProxy", "(Lorg/openqa/selenium/Proxy;)V");
            global::com.codeborne.selenide.WebDriverRunner.j4n_getWebDriver10 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "getWebDriver", "()Lorg/openqa/selenium/WebDriver;");
            global::com.codeborne.selenide.WebDriverRunner.j4n_isHeadless11 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "isHeadless", "()Z");
            global::com.codeborne.selenide.WebDriverRunner.j4n_isSafari12 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "isSafari", "()Z");
            global::com.codeborne.selenide.WebDriverRunner.j4n_isFirefox13 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "isFirefox", "()Z");
            global::com.codeborne.selenide.WebDriverRunner.j4n_isChrome14 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "isChrome", "()Z");
            global::com.codeborne.selenide.WebDriverRunner.j4n_getAndCheckWebDriver15 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "getAndCheckWebDriver", "()Lorg/openqa/selenium/WebDriver;");
            global::com.codeborne.selenide.WebDriverRunner.j4n_hasWebDriverStarted16 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "hasWebDriverStarted", "()Z");
            global::com.codeborne.selenide.WebDriverRunner.j4n_supportsModalDialogs17 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "supportsModalDialogs", "()Z");
            global::com.codeborne.selenide.WebDriverRunner.j4n_clearBrowserCache18 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "clearBrowserCache", "()V");
            global::com.codeborne.selenide.WebDriverRunner.j4n_currentFrameUrl19 = @__env.GetStaticMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "currentFrameUrl", "()Ljava/lang/String;");
            global::com.codeborne.selenide.WebDriverRunner.j4n_webdriverContainer20 = @__env.GetStaticFieldID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "webdriverContainer", "Lcom/codeborne/selenide/impl/WebDriverContainer;");
            global::com.codeborne.selenide.WebDriverRunner.j4n_CHROME21 = @__env.GetStaticFieldID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "CHROME", "Ljava/lang/String;");
            global::com.codeborne.selenide.WebDriverRunner.j4n_INTERNET_EXPLORER22 = @__env.GetStaticFieldID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "INTERNET_EXPLORER", "Ljava/lang/String;");
            global::com.codeborne.selenide.WebDriverRunner.j4n_FIREFOX23 = @__env.GetStaticFieldID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "FIREFOX", "Ljava/lang/String;");
            global::com.codeborne.selenide.WebDriverRunner.j4n_SAFARI24 = @__env.GetStaticFieldID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "SAFARI", "Ljava/lang/String;");
            global::com.codeborne.selenide.WebDriverRunner.j4n_HTMLUNIT25 = @__env.GetStaticFieldID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "HTMLUNIT", "Ljava/lang/String;");
            global::com.codeborne.selenide.WebDriverRunner.j4n_PHANTOMJS26 = @__env.GetStaticFieldID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "PHANTOMJS", "Ljava/lang/String;");
            global::com.codeborne.selenide.WebDriverRunner.j4n_OPERA27 = @__env.GetStaticFieldID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "OPERA", "Ljava/lang/String;");
            global::com.codeborne.selenide.WebDriverRunner.j4n__ctorWebDriverRunner28 = @__env.GetMethodID(global::com.codeborne.selenide.WebDriverRunner.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public static global::java.lang.String url() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_url0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public static bool isPhantomjs() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_isPhantomjs1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/support/events/WebDriverEventListener;)V")]
        public static void addListener(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_addListener2, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public static void closeWebDriver() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_closeWebDriver3);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public static bool isOpera() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_isOpera4)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public static global::java.lang.String source() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_source5));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public static bool isIE() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_isIE6)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public static bool isHtmlUnit() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_isHtmlUnit7)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebDriver;)V")]
        public static void setWebDriver(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_setWebDriver8, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/Proxy;)V")]
        public static void setProxy(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_setProxy9, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/openqa/selenium/WebDriver;")]
        public static global::java.lang.Object getWebDriver() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_getWebDriver10));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public static bool isHeadless() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_isHeadless11)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public static bool isSafari() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_isSafari12)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public static bool isFirefox() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_isFirefox13)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public static bool isChrome() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_isChrome14)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/openqa/selenium/WebDriver;")]
        public static global::java.lang.Object getAndCheckWebDriver() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_getAndCheckWebDriver15));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public static bool hasWebDriverStarted() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_hasWebDriverStarted16)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public static bool supportsModalDialogs() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallStaticBooleanMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_supportsModalDialogs17)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public static void clearBrowserCache() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallStaticVoidMethod(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_clearBrowserCache18);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public static global::java.lang.String currentFrameUrl() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.WebDriverRunner.staticClass, global::com.codeborne.selenide.WebDriverRunner.j4n_currentFrameUrl19));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.WebDriverRunner(@__env);
            }
        }
    }
    #endregion
}
