//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.impl {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class ElementFinder : global::com.codeborne.selenide.impl.WebElementSource {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_wrap0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_wrap1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_wrap2;
        
        protected ElementFinder(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.impl.ElementFinder.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.impl.ElementFinder.staticClass = @__class;
            global::com.codeborne.selenide.impl.ElementFinder.j4n_wrap0 = @__env.GetStaticMethodID(global::com.codeborne.selenide.impl.ElementFinder.staticClass, "wrap", "(Lorg/openqa/selenium/By;)Lcom/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.impl.ElementFinder.j4n_wrap1 = @__env.GetStaticMethodID(global::com.codeborne.selenide.impl.ElementFinder.staticClass, "wrap", "(Ljava/lang/Class;Lorg/openqa/selenium/SearchContext;Lorg/openqa/selenium/By;I)Lc" +
                    "om/codeborne/selenide/SelenideElement;");
            global::com.codeborne.selenide.impl.ElementFinder.j4n_wrap2 = @__env.GetStaticMethodID(global::com.codeborne.selenide.impl.ElementFinder.staticClass, "wrap", "(Lorg/openqa/selenium/SearchContext;Lorg/openqa/selenium/By;I)Lcom/codeborne/sele" +
                    "nide/SelenideElement;");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/By;)Lcom/codeborne/selenide/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement wrap(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.impl.ElementFinder.staticClass, global::com.codeborne.selenide.impl.ElementFinder.j4n_wrap0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Class;Lorg/openqa/selenium/SearchContext;Lorg/openqa/selenium/By;I)Lc" +
            "om/codeborne/selenide/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement wrap(global::java.lang.Class par0, global::java.lang.Object par1, global::java.lang.Object par2, int par3) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 18)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.impl.ElementFinder.staticClass, global::com.codeborne.selenide.impl.ElementFinder.j4n_wrap1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par3)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/SearchContext;Lorg/openqa/selenium/By;I)Lcom/codeborne/sele" +
            "nide/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement wrap(global::java.lang.Object par0, global::java.lang.Object par1, int par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.impl.ElementFinder.staticClass, global::com.codeborne.selenide.impl.ElementFinder.j4n_wrap2, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par2)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.impl.ElementFinder(@__env);
            }
        }
    }
    #endregion
}
