//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.impl {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class Events : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fireChangeEvent0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fireEvent1;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_events2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorEvents3;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public Events() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.codeborne.selenide.impl.Events.staticClass, global::com.codeborne.selenide.impl.Events.j4n__ctorEvents3, this);
            }
        }
        
        protected Events(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.impl.Events.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/impl/Events;")]
        public static global::com.codeborne.selenide.impl.Events events {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.impl.Events>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.impl.Events.staticClass, global::com.codeborne.selenide.impl.Events.j4n_events2));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.impl.Events.staticClass = @__class;
            global::com.codeborne.selenide.impl.Events.j4n_fireChangeEvent0 = @__env.GetMethodID(global::com.codeborne.selenide.impl.Events.staticClass, "fireChangeEvent", "(Lorg/openqa/selenium/WebElement;)V");
            global::com.codeborne.selenide.impl.Events.j4n_fireEvent1 = @__env.GetMethodID(global::com.codeborne.selenide.impl.Events.staticClass, "fireEvent", "(Lorg/openqa/selenium/WebElement;[Ljava/lang/String;)V");
            global::com.codeborne.selenide.impl.Events.j4n_events2 = @__env.GetStaticFieldID(global::com.codeborne.selenide.impl.Events.staticClass, "events", "Lcom/codeborne/selenide/impl/Events;");
            global::com.codeborne.selenide.impl.Events.j4n__ctorEvents3 = @__env.GetMethodID(global::com.codeborne.selenide.impl.Events.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebElement;)V")]
        public virtual void fireChangeEvent(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.impl.Events.j4n_fireChangeEvent0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebElement;[Ljava/lang/String;)V")]
        public virtual void fireEvent(global::java.lang.Object par0, global::java.lang.String[] par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.impl.Events.j4n_fireEvent1, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par1));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.impl.Events(@__env);
            }
        }
    }
    #endregion
}
