//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.impl {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class FilteringCollection : global::java.lang.Object, global::com.codeborne.selenide.impl.WebElementsCollection {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_description0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getActualElements1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorFilteringCollection2;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/impl/WebElementsCollection;Lcom/google/common/base/Predi" +
            "cate;)V")]
        public FilteringCollection(global::com.codeborne.selenide.impl.WebElementsCollection par0, global::java.lang.Object par1) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.NewObject(global::com.codeborne.selenide.impl.FilteringCollection.staticClass, global::com.codeborne.selenide.impl.FilteringCollection.j4n__ctorFilteringCollection2, this, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::com.codeborne.selenide.impl.WebElementsCollection>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par1));
            }
        }
        
        protected FilteringCollection(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.impl.FilteringCollection.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.impl.FilteringCollection.staticClass = @__class;
            global::com.codeborne.selenide.impl.FilteringCollection.j4n_description0 = @__env.GetMethodID(global::com.codeborne.selenide.impl.FilteringCollection.staticClass, "description", "()Ljava/lang/String;");
            global::com.codeborne.selenide.impl.FilteringCollection.j4n_getActualElements1 = @__env.GetMethodID(global::com.codeborne.selenide.impl.FilteringCollection.staticClass, "getActualElements", "()Ljava/util/List;");
            global::com.codeborne.selenide.impl.FilteringCollection.j4n__ctorFilteringCollection2 = @__env.GetMethodID(global::com.codeborne.selenide.impl.FilteringCollection.staticClass, "<init>", "(Lcom/codeborne/selenide/impl/WebElementsCollection;Lcom/google/common/base/Predi" +
                    "cate;)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String description() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.FilteringCollection.j4n_description0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/List;")]
        public virtual global::java.util.List getActualElements() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.List>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.FilteringCollection.j4n_getActualElements1));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.impl.FilteringCollection(@__env);
            }
        }
    }
    #endregion
}
