//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.impl {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class SelenideElementIterator : global::java.lang.Object, global::java.util.Iterator {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_remove0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_hasNext1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_next2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorSelenideElementIterator3;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/util/Iterator;)V")]
        public SelenideElementIterator(global::java.util.Iterator par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::com.codeborne.selenide.impl.SelenideElementIterator.staticClass, global::com.codeborne.selenide.impl.SelenideElementIterator.j4n__ctorSelenideElementIterator3, this, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.Iterator>(@__env, par0));
            }
        }
        
        protected SelenideElementIterator(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.impl.SelenideElementIterator.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.impl.SelenideElementIterator.staticClass = @__class;
            global::com.codeborne.selenide.impl.SelenideElementIterator.j4n_remove0 = @__env.GetMethodID(global::com.codeborne.selenide.impl.SelenideElementIterator.staticClass, "remove", "()V");
            global::com.codeborne.selenide.impl.SelenideElementIterator.j4n_hasNext1 = @__env.GetMethodID(global::com.codeborne.selenide.impl.SelenideElementIterator.staticClass, "hasNext", "()Z");
            global::com.codeborne.selenide.impl.SelenideElementIterator.j4n_next2 = @__env.GetMethodID(global::com.codeborne.selenide.impl.SelenideElementIterator.staticClass, "next", "()Ljava/lang/Object;");
            global::com.codeborne.selenide.impl.SelenideElementIterator.j4n__ctorSelenideElementIterator3 = @__env.GetMethodID(global::com.codeborne.selenide.impl.SelenideElementIterator.staticClass, "<init>", "(Ljava/util/Iterator;)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void remove() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.impl.SelenideElementIterator.j4n_remove0);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool hasNext() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.codeborne.selenide.impl.SelenideElementIterator.j4n_hasNext1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/Object;")]
        public virtual global::java.lang.Object next() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.SelenideElementIterator.j4n_next2));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.impl.SelenideElementIterator(@__env);
            }
        }
    }
    #endregion
}
