//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.impl {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class WebDriverThreadLocalContainer : global::java.lang.Object, global::com.codeborne.selenide.impl.WebDriverContainer {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_addListener0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_closeWebDriver1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getPageSource2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getCurrentUrl3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setWebDriver4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setProxy5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getWebDriver6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getAndCheckWebDriver7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_hasWebDriverStarted8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_clearBrowserCache9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getCurrentFrameUrl10;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorWebDriverThreadLocalContainer11;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public WebDriverThreadLocalContainer() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n__ctorWebDriverThreadLocalContainer11, this);
            }
        }
        
        protected WebDriverThreadLocalContainer(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass = @__class;
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_addListener0 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, "addListener", "(Lorg/openqa/selenium/support/events/WebDriverEventListener;)V");
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_closeWebDriver1 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, "closeWebDriver", "()V");
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_getPageSource2 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, "getPageSource", "()Ljava/lang/String;");
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_getCurrentUrl3 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, "getCurrentUrl", "()Ljava/lang/String;");
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_setWebDriver4 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, "setWebDriver", "(Lorg/openqa/selenium/WebDriver;)Lorg/openqa/selenium/WebDriver;");
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_setProxy5 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, "setProxy", "(Lorg/openqa/selenium/Proxy;)V");
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_getWebDriver6 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, "getWebDriver", "()Lorg/openqa/selenium/WebDriver;");
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_getAndCheckWebDriver7 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, "getAndCheckWebDriver", "()Lorg/openqa/selenium/WebDriver;");
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_hasWebDriverStarted8 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, "hasWebDriverStarted", "()Z");
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_clearBrowserCache9 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, "clearBrowserCache", "()V");
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_getCurrentFrameUrl10 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, "getCurrentFrameUrl", "()Ljava/lang/String;");
            global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n__ctorWebDriverThreadLocalContainer11 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/support/events/WebDriverEventListener;)V")]
        public virtual void addListener(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_addListener0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void closeWebDriver() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_closeWebDriver1);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getPageSource() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_getPageSource2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getCurrentUrl() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_getCurrentUrl3));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebDriver;)Lorg/openqa/selenium/WebDriver;")]
        public virtual global::java.lang.Object setWebDriver(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_setWebDriver4, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/Proxy;)V")]
        public virtual void setProxy(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_setProxy5, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/openqa/selenium/WebDriver;")]
        public virtual global::java.lang.Object getWebDriver() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_getWebDriver6));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/openqa/selenium/WebDriver;")]
        public virtual global::java.lang.Object getAndCheckWebDriver() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_getAndCheckWebDriver7));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool hasWebDriverStarted() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_hasWebDriverStarted8)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void clearBrowserCache() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_clearBrowserCache9);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getCurrentFrameUrl() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer.j4n_getCurrentFrameUrl10));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.impl.WebDriverThreadLocalContainer(@__env);
            }
        }
    }
    #endregion
}
