//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.commands {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class Commands : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_add0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_execute1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_resetDefaults2;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_collection3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorCommands4;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public Commands() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.codeborne.selenide.commands.Commands.staticClass, global::com.codeborne.selenide.commands.Commands.j4n__ctorCommands4, this);
            }
        }
        
        protected Commands(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.commands.Commands.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/commands/Commands;")]
        public static global::com.codeborne.selenide.commands.Commands collection {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.commands.Commands>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.commands.Commands.staticClass, global::com.codeborne.selenide.commands.Commands.j4n_collection3));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.commands.Commands.staticClass = @__class;
            global::com.codeborne.selenide.commands.Commands.j4n_add0 = @__env.GetMethodID(global::com.codeborne.selenide.commands.Commands.staticClass, "add", "(Ljava/lang/String;Lcom/codeborne/selenide/Command;)V");
            global::com.codeborne.selenide.commands.Commands.j4n_execute1 = @__env.GetMethodID(global::com.codeborne.selenide.commands.Commands.staticClass, "execute", "(Ljava/lang/Object;Lcom/codeborne/selenide/impl/WebElementSource;Ljava/lang/Strin" +
                    "g;[Ljava/lang/Object;)Ljava/lang/Object;");
            global::com.codeborne.selenide.commands.Commands.j4n_resetDefaults2 = @__env.GetMethodID(global::com.codeborne.selenide.commands.Commands.staticClass, "resetDefaults", "()V");
            global::com.codeborne.selenide.commands.Commands.j4n_collection3 = @__env.GetStaticFieldID(global::com.codeborne.selenide.commands.Commands.staticClass, "collection", "Lcom/codeborne/selenide/commands/Commands;");
            global::com.codeborne.selenide.commands.Commands.j4n__ctorCommands4 = @__env.GetMethodID(global::com.codeborne.selenide.commands.Commands.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Lcom/codeborne/selenide/Command;)V")]
        public virtual void add(global::java.lang.String par0, global::com.codeborne.selenide.Command par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.commands.Commands.j4n_add0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::com.codeborne.selenide.Command>(@__env, par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Object;Lcom/codeborne/selenide/impl/WebElementSource;Ljava/lang/Strin" +
            "g;[Ljava/lang/Object;)Ljava/lang/Object;")]
        public virtual global::java.lang.Object execute(global::java.lang.Object par0, global::com.codeborne.selenide.impl.WebElementSource par1, global::java.lang.String par2, global::java.lang.Object[] par3) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 18)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.commands.Commands.j4n_execute1, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2), global::net.sf.jni4net.utils.Convertor.ParArrayFullC2J<global::java.lang.Object[], global::java.lang.Object>(@__env, par3)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public void resetDefaults() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.codeborne.selenide.commands.Commands.j4n_resetDefaults2);
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.commands.Commands(@__env);
            }
        }
    }
    #endregion
}
