//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.impl {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class WebElementSource : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_find0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_findAll1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_findAndAssertElementIsVisible2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_checkCondition3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_createElementNotFoundError4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getWebElement5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getSelector6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getSearchCriteria7;
        
        protected WebElementSource(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.impl.WebElementSource.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.impl.WebElementSource.staticClass = @__class;
            global::com.codeborne.selenide.impl.WebElementSource.j4n_find0 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebElementSource.staticClass, "find", "(Lcom/codeborne/selenide/SelenideElement;Ljava/lang/Object;I)Lcom/codeborne/selen" +
                    "ide/SelenideElement;");
            global::com.codeborne.selenide.impl.WebElementSource.j4n_findAll1 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebElementSource.staticClass, "findAll", "()Ljava/util/List;");
            global::com.codeborne.selenide.impl.WebElementSource.j4n_findAndAssertElementIsVisible2 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebElementSource.staticClass, "findAndAssertElementIsVisible", "()Lorg/openqa/selenium/WebElement;");
            global::com.codeborne.selenide.impl.WebElementSource.j4n_checkCondition3 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebElementSource.staticClass, "checkCondition", "(Ljava/lang/String;Ljava/lang/String;Lcom/codeborne/selenide/Condition;Z)Lorg/ope" +
                    "nqa/selenium/WebElement;");
            global::com.codeborne.selenide.impl.WebElementSource.j4n_createElementNotFoundError4 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebElementSource.staticClass, "createElementNotFoundError", "(Lcom/codeborne/selenide/Condition;Ljava/lang/Throwable;)Lcom/codeborne/selenide/" +
                    "ex/ElementNotFound;");
            global::com.codeborne.selenide.impl.WebElementSource.j4n_getWebElement5 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebElementSource.staticClass, "getWebElement", "()Lorg/openqa/selenium/WebElement;");
            global::com.codeborne.selenide.impl.WebElementSource.j4n_getSelector6 = @__env.GetStaticMethodID(global::com.codeborne.selenide.impl.WebElementSource.staticClass, "getSelector", "(Ljava/lang/Object;)Lorg/openqa/selenium/By;");
            global::com.codeborne.selenide.impl.WebElementSource.j4n_getSearchCriteria7 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebElementSource.staticClass, "getSearchCriteria", "()Ljava/lang/String;");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/SelenideElement;Ljava/lang/Object;I)Lcom/codeborne/selen" +
            "ide/SelenideElement;")]
        public virtual global::com.codeborne.selenide.SelenideElement find(global::com.codeborne.selenide.SelenideElement par0, global::java.lang.Object par1, int par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebElementSource.j4n_find0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::com.codeborne.selenide.SelenideElement>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/List;")]
        public virtual global::java.util.List findAll() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.List>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebElementSource.j4n_findAll1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/openqa/selenium/WebElement;")]
        public virtual global::java.lang.Object findAndAssertElementIsVisible() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebElementSource.j4n_findAndAssertElementIsVisible2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;Lcom/codeborne/selenide/Condition;Z)Lorg/ope" +
            "nqa/selenium/WebElement;")]
        public virtual global::java.lang.Object checkCondition(global::java.lang.String par0, global::java.lang.String par1, global::com.codeborne.selenide.Condition par2, bool par3) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 18)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebElementSource.j4n_checkCondition3, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par3)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/codeborne/selenide/Condition;Ljava/lang/Throwable;)Lcom/codeborne/selenide/" +
            "ex/ElementNotFound;")]
        public virtual global::com.codeborne.selenide.ex.ElementNotFound createElementNotFoundError(global::com.codeborne.selenide.Condition par0, global::java.lang.Throwable par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.ex.ElementNotFound>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebElementSource.j4n_createElementNotFoundError4, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Throwable>(@__env, par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lorg/openqa/selenium/WebElement;")]
        public virtual global::java.lang.Object getWebElement() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebElementSource.j4n_getWebElement5));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Object;)Lorg/openqa/selenium/By;")]
        public static global::java.lang.Object getSelector(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.impl.WebElementSource.staticClass, global::com.codeborne.selenide.impl.WebElementSource.j4n_getSelector6, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getSearchCriteria() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebElementSource.j4n_getSearchCriteria7));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.impl.WebElementSource(@__env);
            }
        }
    }
    #endregion
}
