//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.impl {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class WebElementSelector : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_findElements0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_findElement1;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_instance2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorWebElementSelector3;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public WebElementSelector() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.codeborne.selenide.impl.WebElementSelector.staticClass, global::com.codeborne.selenide.impl.WebElementSelector.j4n__ctorWebElementSelector3, this);
            }
        }
        
        protected WebElementSelector(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.impl.WebElementSelector.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/codeborne/selenide/impl/WebElementSelector;")]
        public static global::com.codeborne.selenide.impl.WebElementSelector instance {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.codeborne.selenide.impl.WebElementSelector>(@__env, @__env.GetStaticObjectFieldPtr(global::com.codeborne.selenide.impl.WebElementSelector.staticClass, global::com.codeborne.selenide.impl.WebElementSelector.j4n_instance2));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.impl.WebElementSelector.staticClass = @__class;
            global::com.codeborne.selenide.impl.WebElementSelector.j4n_findElements0 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebElementSelector.staticClass, "findElements", "(Lorg/openqa/selenium/SearchContext;Lorg/openqa/selenium/By;)Ljava/util/List;");
            global::com.codeborne.selenide.impl.WebElementSelector.j4n_findElement1 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebElementSelector.staticClass, "findElement", "(Lorg/openqa/selenium/SearchContext;Lorg/openqa/selenium/By;)Lorg/openqa/selenium" +
                    "/WebElement;");
            global::com.codeborne.selenide.impl.WebElementSelector.j4n_instance2 = @__env.GetStaticFieldID(global::com.codeborne.selenide.impl.WebElementSelector.staticClass, "instance", "Lcom/codeborne/selenide/impl/WebElementSelector;");
            global::com.codeborne.selenide.impl.WebElementSelector.j4n__ctorWebElementSelector3 = @__env.GetMethodID(global::com.codeborne.selenide.impl.WebElementSelector.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/SearchContext;Lorg/openqa/selenium/By;)Ljava/util/List;")]
        public virtual global::java.util.List findElements(global::java.lang.Object par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.List>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebElementSelector.j4n_findElements0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/SearchContext;Lorg/openqa/selenium/By;)Lorg/openqa/selenium" +
            "/WebElement;")]
        public virtual global::java.lang.Object findElement(global::java.lang.Object par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.codeborne.selenide.impl.WebElementSelector.j4n_findElement1, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.impl.WebElementSelector(@__env);
            }
        }
    }
    #endregion
}
