//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.impl {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class WebElementWrapper : global::com.codeborne.selenide.impl.WebElementSource {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_wrap0;
        
        protected WebElementWrapper(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.impl.WebElementWrapper.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.impl.WebElementWrapper.staticClass = @__class;
            global::com.codeborne.selenide.impl.WebElementWrapper.j4n_wrap0 = @__env.GetStaticMethodID(global::com.codeborne.selenide.impl.WebElementWrapper.staticClass, "wrap", "(Lorg/openqa/selenium/WebElement;)Lcom/codeborne/selenide/SelenideElement;");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lorg/openqa/selenium/WebElement;)Lcom/codeborne/selenide/SelenideElement;")]
        public static global::com.codeborne.selenide.SelenideElement wrap(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.codeborne.selenide.SelenideElement>(@__env, @__env.CallStaticObjectMethodPtr(global::com.codeborne.selenide.impl.WebElementWrapper.staticClass, global::com.codeborne.selenide.impl.WebElementWrapper.j4n_wrap0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.impl.WebElementWrapper(@__env);
            }
        }
    }
    #endregion
}
