//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.ex {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    [global::System.SerializableAttribute()]
    public partial class ElementShould : global::com.codeborne.selenide.ex.UIAssertionError {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_timeoutMs0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorElementShould1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorElementShould2;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;Lcom/codeborne/selenide/Condition;Lorg/openq" +
            "a/selenium/WebElement;Ljava/lang/Exception;)V")]
        public ElementShould(global::java.lang.String par0, global::java.lang.String par1, global::com.codeborne.selenide.Condition par2, global::java.lang.Object par3, global::java.lang.Exception par4) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 20)){
            @__env.NewObject(global::com.codeborne.selenide.ex.ElementShould.staticClass, global::com.codeborne.selenide.ex.ElementShould.j4n__ctorElementShould1, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par3), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par4));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/codeborne/selenide/Co" +
            "ndition;Lorg/openqa/selenium/WebElement;Ljava/lang/Throwable;)V")]
        public ElementShould(global::java.lang.String par0, global::java.lang.String par1, global::java.lang.String par2, global::com.codeborne.selenide.Condition par3, global::java.lang.Object par4, global::java.lang.Throwable par5) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 22)){
            @__env.NewObject(global::com.codeborne.selenide.ex.ElementShould.staticClass, global::com.codeborne.selenide.ex.ElementShould.j4n__ctorElementShould2, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par3), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par4), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Throwable>(@__env, par5));
            }
        }
        
        protected ElementShould(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        protected ElementShould(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.ex.ElementShould.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("J")]
        public virtual long timeoutMs {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((long)(@__env.GetLongField(this, global::com.codeborne.selenide.ex.ElementShould.j4n_timeoutMs0)));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.ex.ElementShould.staticClass = @__class;
            global::com.codeborne.selenide.ex.ElementShould.j4n_timeoutMs0 = @__env.GetFieldID(global::com.codeborne.selenide.ex.ElementShould.staticClass, "timeoutMs", "J");
            global::com.codeborne.selenide.ex.ElementShould.j4n__ctorElementShould1 = @__env.GetMethodID(global::com.codeborne.selenide.ex.ElementShould.staticClass, "<init>", "(Ljava/lang/String;Ljava/lang/String;Lcom/codeborne/selenide/Condition;Lorg/openq" +
                    "a/selenium/WebElement;Ljava/lang/Exception;)V");
            global::com.codeborne.selenide.ex.ElementShould.j4n__ctorElementShould2 = @__env.GetMethodID(global::com.codeborne.selenide.ex.ElementShould.staticClass, "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/codeborne/selenide/Co" +
                    "ndition;Lorg/openqa/selenium/WebElement;Ljava/lang/Throwable;)V");
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.ex.ElementShould(@__env);
            }
        }
    }
    #endregion
}
