//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.ex {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    [global::System.SerializableAttribute()]
    public partial class JavaScriptErrorsFound : global::com.codeborne.selenide.ex.UIAssertionError {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_timeoutMs0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorJavaScriptErrorsFound1;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/util/List;)V")]
        public JavaScriptErrorsFound(global::java.util.List par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::com.codeborne.selenide.ex.JavaScriptErrorsFound.staticClass, global::com.codeborne.selenide.ex.JavaScriptErrorsFound.j4n__ctorJavaScriptErrorsFound1, this, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.List>(@__env, par0));
            }
        }
        
        protected JavaScriptErrorsFound(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        protected JavaScriptErrorsFound(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.ex.JavaScriptErrorsFound.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("J")]
        public virtual long timeoutMs {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((long)(@__env.GetLongField(this, global::com.codeborne.selenide.ex.JavaScriptErrorsFound.j4n_timeoutMs0)));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.ex.JavaScriptErrorsFound.staticClass = @__class;
            global::com.codeborne.selenide.ex.JavaScriptErrorsFound.j4n_timeoutMs0 = @__env.GetFieldID(global::com.codeborne.selenide.ex.JavaScriptErrorsFound.staticClass, "timeoutMs", "J");
            global::com.codeborne.selenide.ex.JavaScriptErrorsFound.j4n__ctorJavaScriptErrorsFound1 = @__env.GetMethodID(global::com.codeborne.selenide.ex.JavaScriptErrorsFound.staticClass, "<init>", "(Ljava/util/List;)V");
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.ex.JavaScriptErrorsFound(@__env);
            }
        }
    }
    #endregion
}
