//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.codeborne.selenide.ex {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    [global::System.SerializableAttribute()]
    public partial class ListSizeMismatch : global::com.codeborne.selenide.ex.UIAssertionError {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_timeoutMs0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorListSizeMismatch1;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(ILcom/codeborne/selenide/impl/WebElementsCollection;Ljava/util/List;Ljava/lang/E" +
            "xception;J)V")]
        public ListSizeMismatch(int par0, global::com.codeborne.selenide.impl.WebElementsCollection par1, global::java.util.List par2, global::java.lang.Exception par3, long par4) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 20)){
            @__env.NewObject(global::com.codeborne.selenide.ex.ListSizeMismatch.staticClass, global::com.codeborne.selenide.ex.ListSizeMismatch.j4n__ctorListSizeMismatch1, this, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::com.codeborne.selenide.impl.WebElementsCollection>(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.List>(@__env, par2), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par3), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par4));
            }
        }
        
        protected ListSizeMismatch(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        protected ListSizeMismatch(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.codeborne.selenide.ex.ListSizeMismatch.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("J")]
        public virtual long timeoutMs {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((long)(@__env.GetLongField(this, global::com.codeborne.selenide.ex.ListSizeMismatch.j4n_timeoutMs0)));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.codeborne.selenide.ex.ListSizeMismatch.staticClass = @__class;
            global::com.codeborne.selenide.ex.ListSizeMismatch.j4n_timeoutMs0 = @__env.GetFieldID(global::com.codeborne.selenide.ex.ListSizeMismatch.staticClass, "timeoutMs", "J");
            global::com.codeborne.selenide.ex.ListSizeMismatch.j4n__ctorListSizeMismatch1 = @__env.GetMethodID(global::com.codeborne.selenide.ex.ListSizeMismatch.staticClass, "<init>", "(ILcom/codeborne/selenide/impl/WebElementsCollection;Ljava/util/List;Ljava/lang/E" +
                    "xception;J)V");
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.codeborne.selenide.ex.ListSizeMismatch(@__env);
            }
        }
    }
    #endregion
}
